
# Nom de notre workflow
name: "Build and deploy Github pages"
on:
  push:         # <- Déclenché lorsque l'on pousse du code...
    branches:
      - master  # <- ... mais seulement sur la branche "master"
    folder: FLAPPY_CLONE